steps:
  - name: 'hashicorp/terraform:light' # Use the Terraform image
    id: init
    args: ['init']
    dir: 'dev' # Directory where your main.tf is located
  - name: 'hashicorp/terraform:light'
    id: plan
    args: ['plan', '-out=tfplan']
    dir: 'terraform'
  - name: 'hashicorp/terraform:light'
    id: apply
    args: ['apply', '-input=false', 'tfplan']
    dir: 'terraform'
