options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: gs://icos_logbucket

steps:
  - name: 'hashicorp/terraform:light' # Use the Terraform image
    id: init
    args: ['init']
    dir: 'dev' # Directory where your main.tf is located
  - name: 'hashicorp/terraform:light'
    id: plan
    args: ['plan', '-out=tfplan']
    dir: 'terraform'
  - name: 'hashicorp/terraform:light'
    id: apply
    args: ['apply', '-input=false', 'tfplan']
    dir: 'terraform'
 env:
  - 'PROJECT_ID=index-icos-sandbox-e9ddv7  

